# Generated by Django 5.2.18 on 2026-10-08 05:52

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=16)),
                ('sport', models.CharField(max_length=64)),
            ],
            options={
                'constraints': [
                    models.UniqueConstraint(fields=('name',), name='league_name_uniq'),
                    models.UniqueConstraint(
                        fields=('abbreviation',), name='league_abbreviation_uniq'
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('year', models.PositiveSmallIntegerField()),
                (
                    'league',
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='seasons',
                        to='sports.league',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('external_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=16)),
                (
                    'league',
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='teams',
                        to='sports.league',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('external_id', models.CharField(max_length=64)),
                ('week', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('kickoff_at', models.DateTimeField()),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('scheduled', 'Scheduled'),
                            ('in_progress', 'In progress'),
                            ('final', 'Final'),
                            ('postponed', 'Postponed'),
                            ('delayed', 'Delayed'),
                            ('cancelled', 'Cancelled'),
                        ],
                        max_length=16,
                    ),
                ),
                ('home_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('away_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'season',
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='games',
                        to='sports.season',
                    ),
                ),
                (
                    'away_team',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='away_games',
                        to='sports.team',
                    ),
                ),
                (
                    'home_team',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='home_games',
                        to='sports.team',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='GameLine',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('source', models.CharField(max_length=64)),
                ('bookmaker', models.CharField(max_length=64)),
                (
                    'home_spread',
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    'away_spread',
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    'home_spread_price',
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                (
                    'away_spread_price',
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                (
                    'home_moneyline',
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                (
                    'away_moneyline',
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                ('captured_at', models.DateTimeField()),
                (
                    'game',
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='lines',
                        to='sports.game',
                    ),
                ),
            ],
            options={
                'indexes': [
                    models.Index(
                        fields=['game', '-captured_at'],
                        name='gameline_game_captured_idx',
                    )
                ],
                'constraints': [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ('away_spread__isnull', True),
                                ('home_spread__isnull', True),
                            ),
                            (
                                'away_spread',
                                django.db.models.expressions.CombinedExpression(
                                    models.F('home_spread'), '*', models.Value(-1)
                                ),
                            ),
                            _connector='OR',
                        ),
                        name='gameline_spread_opposites',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ('away_moneyline__isnull', True),
                                ('home_moneyline__isnull', True),
                            ),
                            models.Q(
                                ('away_moneyline__gt', 1), ('home_moneyline__gt', 1)
                            ),
                            _connector='OR',
                        ),
                        name='gameline_moneyline_pair',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ('home_spread_price__isnull', True),
                                ('home_spread_price__gt', 1),
                                _connector='OR',
                            ),
                            models.Q(
                                ('away_spread_price__isnull', True),
                                ('away_spread_price__gt', 1),
                                _connector='OR',
                            ),
                        ),
                        name='gameline_spread_prices_gt_one',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ('away_spread__isnull', False),
                                ('home_spread__isnull', False),
                            ),
                            models.Q(
                                ('away_moneyline__isnull', False),
                                ('home_moneyline__isnull', False),
                            ),
                            _connector='OR',
                        ),
                        name='gameline_has_market',
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name='season',
            constraint=models.UniqueConstraint(
                fields=('league', 'year'), name='season_league_year_uniq'
            ),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(
                fields=('league', 'external_id'), name='team_league_external_id_uniq'
            ),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(
                fields=('league', 'abbreviation'), name='team_league_abbreviation_uniq'
            ),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['season', 'week'], name='game_season_week_idx'),
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.UniqueConstraint(
                fields=('external_id',), name='game_external_id_uniq'
            ),
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.CheckConstraint(
                condition=models.Q(('home_team', models.F('away_team')), _negated=True),
                name='game_home_away_differ',
            ),
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        'status__in',
                        [
                            'scheduled',
                            'in_progress',
                            'final',
                            'postponed',
                            'delayed',
                            'cancelled',
                        ],
                    )
                ),
                name='game_status_known',
            ),
        ),
    ]
