# Generated by Django 5.2.18 on 2026-10-09 20:50

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='gameline',
            name='gameline_spread_opposites',
        ),
        migrations.RemoveConstraint(
            model_name='gameline',
            name='gameline_moneyline_pair',
        ),
        migrations.AddConstraint(
            model_name='gameline',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ('away_spread__isnull', True), ('home_spread__isnull', True)
                    ),
                    models.Q(
                        ('away_spread__isnull', False),
                        ('home_spread__isnull', False),
                        (
                            'away_spread',
                            django.db.models.expressions.CombinedExpression(
                                models.F('home_spread'), '*', models.Value(-1)
                            ),
                        ),
                    ),
                    _connector='OR',
                ),
                name='gameline_spread_opposites',
            ),
        ),
        migrations.AddConstraint(
            model_name='gameline',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ('away_moneyline__isnull', True),
                        ('home_moneyline__isnull', True),
                    ),
                    models.Q(
                        ('away_moneyline__isnull', False),
                        ('home_moneyline__isnull', False),
                        ('away_moneyline__gt', 1),
                        ('home_moneyline__gt', 1),
                    ),
                    _connector='OR',
                ),
                name='gameline_moneyline_pair',
            ),
        ),
    ]
