# Generated by Django 5.2.18 on 2026-10-08 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('sports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pick',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'pick_type',
                    models.CharField(
                        choices=[('spread', 'Spread'), ('moneyline', 'Moneyline')],
                        max_length=16,
                    ),
                ),
                (
                    'line_value',
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    'price',
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                (
                    'result',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('win', 'Win'),
                            ('loss', 'Loss'),
                            ('push', 'Push'),
                            ('void', 'Void'),
                        ],
                        max_length=8,
                        null=True,
                    ),
                ),
                (
                    'points',
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                (
                    'game',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='picks',
                        to='sports.game',
                    ),
                ),
                (
                    'game_line',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='picks',
                        to='sports.gameline',
                    ),
                ),
                (
                    'picked_team',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='picked_picks',
                        to='sports.team',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='picks',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'indexes': [
                    models.Index(
                        fields=['user', '-submitted_at'], name='pick_user_submitted_idx'
                    )
                ],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('user', 'game', 'pick_type'),
                        name='pick_user_game_type_uniq',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ('line_value__isnull', False), ('pick_type', 'spread')
                            ),
                            models.Q(
                                ('pick_type', 'moneyline'), ('price__isnull', False)
                            ),
                            _connector='OR',
                        ),
                        name='pick_market_terms_present',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ('result__isnull', True),
                            ('result__in', ['win', 'loss', 'push', 'void']),
                            _connector='OR',
                        ),
                        name='pick_result_known',
                    ),
                ],
            },
        ),
    ]
